USE [master]
GO

/****** Object:  Database [csomagkuldoB]    Script Date: 2023. 11. 07. 8:03:44 ******/
CREATE DATABASE [csomagkuldoB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'csomagkuldoB', FILENAME = N'/var/opt/mssql/data/csomagkuldoB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'csomagkuldoB_log', FILENAME = N'/var/opt/mssql/data/csomagkuldoB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [csomagkuldoB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [csomagkuldoB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [csomagkuldoB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [csomagkuldoB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [csomagkuldoB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [csomagkuldoB] SET ARITHABORT OFF 
GO

ALTER DATABASE [csomagkuldoB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [csomagkuldoB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [csomagkuldoB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [csomagkuldoB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [csomagkuldoB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [csomagkuldoB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [csomagkuldoB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [csomagkuldoB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [csomagkuldoB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [csomagkuldoB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [csomagkuldoB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [csomagkuldoB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [csomagkuldoB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [csomagkuldoB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [csomagkuldoB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [csomagkuldoB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [csomagkuldoB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [csomagkuldoB] SET RECOVERY FULL 
GO

ALTER DATABASE [csomagkuldoB] SET  MULTI_USER 
GO

ALTER DATABASE [csomagkuldoB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [csomagkuldoB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [csomagkuldoB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [csomagkuldoB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [csomagkuldoB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [csomagkuldoB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [csomagkuldoB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [csomagkuldoB] SET  READ_WRITE 
GO

