USE [master]
GO

/****** Object:  Database [csomagkuldoC]    Script Date: 2023. 11. 07. 8:03:59 ******/
CREATE DATABASE [csomagkuldoC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'csomagkuldoC', FILENAME = N'/var/opt/mssql/data/csomagkuldoC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'csomagkuldoC_log', FILENAME = N'/var/opt/mssql/data/csomagkuldoC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [csomagkuldoC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [csomagkuldoC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [csomagkuldoC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [csomagkuldoC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [csomagkuldoC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [csomagkuldoC] SET ARITHABORT OFF 
GO

ALTER DATABASE [csomagkuldoC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [csomagkuldoC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [csomagkuldoC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [csomagkuldoC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [csomagkuldoC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [csomagkuldoC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [csomagkuldoC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [csomagkuldoC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [csomagkuldoC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [csomagkuldoC] SET  ENABLE_BROKER 
GO

ALTER DATABASE [csomagkuldoC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [csomagkuldoC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [csomagkuldoC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [csomagkuldoC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [csomagkuldoC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [csomagkuldoC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [csomagkuldoC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [csomagkuldoC] SET RECOVERY FULL 
GO

ALTER DATABASE [csomagkuldoC] SET  MULTI_USER 
GO

ALTER DATABASE [csomagkuldoC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [csomagkuldoC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [csomagkuldoC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [csomagkuldoC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [csomagkuldoC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [csomagkuldoC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [csomagkuldoC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [csomagkuldoC] SET  READ_WRITE 
GO

