USE [master]
GO

/****** Object:  Database [csomagkuldoA]    Script Date: 2023. 11. 07. 8:03:28 ******/
CREATE DATABASE [csomagkuldoA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'csomagkuldoA', FILENAME = N'/var/opt/mssql/data/csomagkuldoA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'csomagkuldoA_log', FILENAME = N'/var/opt/mssql/data/csomagkuldoA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [csomagkuldoA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [csomagkuldoA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [csomagkuldoA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [csomagkuldoA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [csomagkuldoA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [csomagkuldoA] SET ARITHABORT OFF 
GO

ALTER DATABASE [csomagkuldoA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [csomagkuldoA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [csomagkuldoA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [csomagkuldoA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [csomagkuldoA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [csomagkuldoA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [csomagkuldoA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [csomagkuldoA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [csomagkuldoA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [csomagkuldoA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [csomagkuldoA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [csomagkuldoA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [csomagkuldoA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [csomagkuldoA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [csomagkuldoA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [csomagkuldoA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [csomagkuldoA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [csomagkuldoA] SET RECOVERY FULL 
GO

ALTER DATABASE [csomagkuldoA] SET  MULTI_USER 
GO

ALTER DATABASE [csomagkuldoA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [csomagkuldoA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [csomagkuldoA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [csomagkuldoA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [csomagkuldoA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [csomagkuldoA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [csomagkuldoA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [csomagkuldoA] SET  READ_WRITE 
GO

